In [1]:
#11.1
import numpy as np
np.__version__

'1.21.5'

In [15]:
#11-2

#1
a=np.array([0,0,0,0,0,0,0,0,0])
print('a=',a)

#2
b=np.zeros((10,))
print('b=',b)

#3
type(a)
type(b)

a= [0 0 0 0 0 0 0 0 0]
b= [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.ndarray

In [23]:
#11-3

n_arr=np.array([1,2,3,4,5,6,7,8,9,10],dtype='int32')
print('n_arr의 크기 :{} byte'.format(n_arr.itemsize*n_arr.size))

#1
n_arr=np.array([1,2,3,4,5,6,7,8,9,10],dtype='int64')
print('n_arr의 크기 :{} byte'.format(n_arr.itemsize*n_arr.size))

#2
n_arr=np.array([1.5,2.2,3.2,4.9],dtype='float64')
print('n_arr의 크기 :{} byte'.format(n_arr.itemsize*n_arr.size))

n_arr의 크기 :40 byte
n_arr의 크기 :80 byte
n_arr의 크기 :32 byte


In [28]:
#11-4
#1
a=np.arange(1,11)
print('a=',a)

#2
a=a[::-1]
print('a=',a)

#3
a=a.reshape(2,5)
print('a=',a)

#4
a=a.reshape(5,2)
print('a=',a)

a= [ 1  2  3  4  5  6  7  8  9 10]
a= [10  9  8  7  6  5  4  3  2  1]
a= [[10  9  8  7  6]
 [ 5  4  3  2  1]]
a= [[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [29]:
#11-5

a=np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [33]:
#11-6

a=np.random.random(10)
print('a=',a)

print('최댓값 :',a.max())
print('최솟값 :',a.min())
print('평균값 :',a.mean())

a= [0.51440027 0.90943078 0.92554155 0.92051219 0.12887301 0.71715989
 0.58425037 0.80247282 0.8789445  0.99086088]
최댓값 : 0.9908608849898074
최솟값 : 0.1288730129209943
평균값 : 0.7372446268334167


In [44]:
#11-7
import numpy as np

n=int(input('n을 입력하시오:'))

a=np.ones((n,n))
for i in range(n):
    for j in range(n):
        if (i+j)%2==1:
            a[i,j]=0
print(a)

n을 입력하시오:5
[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


In [15]:
#11-8
import numpy as np

n=int(input('n을 입력하시오:'))

a=np.zeros((n,n))
j=0
for i in range(n):
    j=j+1
    a[i,i]=j

    
print(a)

n을 입력하시오:6
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [18]:
#11-9

import numpy as np

n=int(input('n을 입력하시오:'))
a=np.zeros((n,n))
print('a 행렬')
print(a)
b=np.ones((n,n),dtype='int32')
b[1:-1,1:-1]=0
print('b 행렬')
print(b)

n을 입력하시오:5
a 행렬
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
b 행렬
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [19]:
#11-10
import numpy as np

n=int(input('n을 입력하시오:'))
a=np.ones((n,n))
print('a 행렬')
print(a)
b=np.zeros((n,n))
b[1:-1,1:-1]=1
print('b 행렬')
print(b)

n을 입력하시오:5
a 행렬
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b 행렬
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
#11-13
a=np.array([0,10,20,40,60,80])
b=np.array([0,20])
c = np.array([])

print('a배열 :',a)
print('b배열 :',b)

#1
for n in a:
    if n not in b:
        c = np.append(c, n)
print('a-b배열 :',c)

#2
c=np.setdiff1d(a,b)
print(c)

a배열 : [ 0 10 20 40 60 80]
b배열 : [ 0 20]
a-b배열 : [10. 40. 60. 80.]
[10 40 60 80]


In [40]:
#11-14

n=int(input('n을 입력하시오 :'))
a=np.zeros((n,n))

for i in range(n):
    a[i,i]=1
for j in range(n):
    a[j,n-1-j]=1
print(a)

n을 입력하시오 :6
[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [1]:
#11-15
import numpy as np
#1
n=int(input('n을 입력하시오 :'))
a=np.zeros((n,n))

for i in range(n):
    for j in range(n):
        if i >= j:
            a[i, j] = 1
print(a)    

#2
s=a.sum()
print('행렬의 모든 원소의 합:',s)

s=a.sum(axis=0)
print('행렬의 행방향 성분의 합:',s)

s=a.sum(axis=1)
print('행렬의 열방향 성분의 합:',s)


n을 입력하시오 :5
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
행렬의 모든 원소의 합: 15.0
행렬의 행방향 성분의 합: [5. 4. 3. 2. 1.]
행렬의 열방향 성분의 합: [1. 2. 3. 4. 5.]


In [2]:
#11-20
a=np.array([[2,1,1],[1,2,1],[1,1,2]])
b=np.array([16,9,3])
x=np.linalg.solve(a,b)
print('x={}, y={}, z={}'.format(x[0],x[1],x[2]))

x=9.0, y=2.0, z=-4.0
