In [113]:
#LAB 11-1.1

import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a
#LAB 11-1.2

a=np.array(range(10))
a

#LAB 11-1.3
c=np.array(range(0,10,2))
c

#LAB 11-1.4
c=np.array(range(0,10,2),dtype='int64')

print('c.shape =',c.shape)
print('c.ndim =',c.ndim)
print('c.dtype =',c.dtype)
print('c.size =',c.size)
print('c.itemsize =',c.itemsize)


c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.size = 5
c.itemsize = 8


In [32]:
#LAB 11-2.1
a=np.array([23,45,67,7,2,30,34,82])
print('a= array({})'.format(a))

print('최댓값 :',a.max())
print('최솟값 :',a.min())
print('평균 :',a.mean())

#LAB 11-2.2
b=np.random.randint(0,100,size=10)
print('b=',b)
print('최댓값 :',b.max())
print('최솟값 :',b.min())
print('평균 :',b.mean())

c=np.append(a,b)
print('c=',c)

a= array([23 45 67  7  2 30 34 82])
최댓값 : 82
최솟값 : 2
평균 : 36.25
b= [78 21  9 38 19 70 14  6 80 62]
최댓값 : 80
최솟값 : 6
평균 : 39.7
c= [23 45 67  7  2 30 34 82 78 21  9 38 19 70 14  6 80 62]


In [38]:
#LAB 11-3.1
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,2,2],[2,2,2],[2,2,2]])

print('a=',a)
print('b=',b)
print()
print(a+b)
print()
print(a-b)
print()
print(a*b)
print()
print(a/b)
print()
print(a@b)
print()
print(a**b)



a= [[1 2 3]
 [4 5 6]
 [7 8 9]]
b= [[2 2 2]
 [2 2 2]
 [2 2 2]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

[[12 12 12]
 [30 30 30]
 [48 48 48]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [49]:
#LAB 11-4.1
a1=np.full((3,3),2)
print(a1)
#LAB 11-4.2

a2=np.arange(1,13)
print(a2)

#LAB 11-4.3
a3=np.arange(3,50,3)
print(a3)

#LAB 11-4.4
a4=np.linspace(0,20,5)
print(a4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 0.  5. 10. 15. 20.]


In [59]:
#LAB 11-5.1
import numpy as np
a1=np.arange(1,13).reshape(2,6)
a1

#LAB 11-5.2
a2=np.arange(1,31).reshape(3,10)
a2

#LAB 11-5.3
a3=a2.reshape(6,5)

#LAB 11-5.4
a4=np.transpose(a3)
a4

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [72]:
#LAB 11-6.1
import numpy as np 
a=np.random.randint(1,101,15).reshape(3,5)
print(a)
print()
#LAB 11-6.2
print('a의 열방향 최댓값 :',a.max(axis=0))
print('a의 열방향 최솟값 :',a.min(axis=0))
print('a의 열방향 평균 :',a.mean(axis=0))

print()
#LAB 11-6.3
print('a의 행방향 최댓값 :',a.max(axis=1))
print('a의 행방향 최솟값 :',a.min(axis=1))
print('a의 행방향 평균 :',a.mean(axis=1))

[[73 52 38 26 16]
 [24 77 89 19 89]
 [25 59 61 93 58]]

a의 열방향 최댓값 : [73 77 89 93 89]
a의 열방향 최솟값 : [24 52 38 19 16]
a의 열방향 평균 : [40.66666667 62.66666667 62.66666667 46.         54.33333333]

a의 행방향 최댓값 : [73 89 93]
a의 행방향 최솟값 : [16 19 25]
a의 행방향 평균 : [41.  59.6 59.2]


In [76]:
#11-7.1
a=np.arange(1,11)
print('a=',a[1:9:2])

#11-7.2
print('b=',a[5:])
print('c=',a[6:])
print('a=',a[:3])
print('a=',a[::2])
print('a=',a[::-2])



a= [2 4 6 8]
b= [ 6  7  8  9 10]
c= [ 7  8  9 10]
a= [1 2 3]
a= [1 3 5 7 9]
a= [10  8  6  4  2]


In [3]:
#11-8.1
import numpy as np
a = np.arange(0, 24).reshape(4, 3, 2)

print('{:13s}{:5s}'.format('index', 'element'))
for i in np.ndindex(a.shape):
    print('{}{:7d}'.format(i, a[i]))
    
    
    
#11-8.2
np.concatenate((a[0, 0], a[1, 0]), axis=0)


np.concatenate((a[0, 0], a[2, 1]), axis=0)

np.concatenate((a[0], a[1]), axis=0)

np.concatenate((a[0], a[1]), axis=1)

np.concatenate((a[0, 0], a[1, 0]), axis=0)

index        element
(0, 0, 0)      0
(0, 0, 1)      1
(0, 1, 0)      2
(0, 1, 1)      3
(0, 2, 0)      4
(0, 2, 1)      5
(1, 0, 0)      6
(1, 0, 1)      7
(1, 1, 0)      8
(1, 1, 1)      9
(1, 2, 0)     10
(1, 2, 1)     11
(2, 0, 0)     12
(2, 0, 1)     13
(2, 1, 0)     14
(2, 1, 1)     15
(2, 2, 0)     16
(2, 2, 1)     17
(3, 0, 0)     18
(3, 0, 1)     19
(3, 1, 0)     20
(3, 1, 1)     21
(3, 2, 0)     22
(3, 2, 1)     23


array([0, 1, 6, 7])

In [105]:
#11-9.1
a=np.arange(0,16).reshape(4,4)

print('b=',a[:,1])
print('c=',a[2,1:])
print('d=',a[0:2,0:2])
print('e=',a[1:3,1:3])

#11-9.2
f=a[:3,:2].flatten()

print('f=',f)
print('g=',a[2:,:].flatten())


print('h=',a[1::2,1:].flatten())

b= [ 1  5  9 13]
c= [ 9 10 11]
d= [[0 1]
 [4 5]]
e= [[ 5  6]
 [ 9 10]]
f= [0 1 4 5 8 9]
g= [ 8  9 10 11 12 13 14 15]
h= [ 5  6  7 13 14 15]


In [10]:
#11-10.1

import numpy as np
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype='int32')
B = np.array([0, 9, 8], dtype='int32')
x = np.linalg.solve(A, B)
print('x =',x[0],'y =',x[1], 'z =',  x[2])

#11-10.2
A = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]], dtype='int32')
det = np.linalg.det(A)
print('det(A) = {:4.1f}'.format(det))



x = 1.0000000000000007 y = 2.0 z = 2.9999999999999996
det(A) = -11.0
